# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Nirapod Labs

name: SimBLEExample
options:
  bundleIdPrefix: dev.simble
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
targets: {}
